### ISSUE TITLE
Days left to change your prediction: 269

### ISSUE THREAD

**Issue by emiludev** [efyasar/world-cup-prediction-game#2]
Hi, we have implemented the solution successfully, but we have a question, in the end users application, in the "My Prediction" tab, days left to change your prediction, is set to 264, when in fact it is less than a week from from today.

Is there a way to correct the remaining days.
![Captura de pantalla 2022-11-15 163903](https://user-images.githubusercontent.com/79489808/202039925-c05fe37e-e8c1-4b8a-ac5a-6abc1df19931.png)

**Comment by efyasar** [comment]
Please make sure that you import latest version of the solution package. This issue solved in [last version](https://github.com/efyasar/football-world-championship-prediction-game/wiki/How-to-Update-the-app).
