### ISSUE TITLE
Users can reset predictions whenever they want

### ISSUE THREAD

**Issue by caznaran** [efyasar/world-cup-prediction-game#3]
Is there a way to "lock" predictions and avoid them to be reset?

I mean, what if I reset my predictions at the end of each phase, or what if I reset the predictions right after the finals? That will be unfair.

**Comment by efyasar** [comment]
By default, the app only allows making new predictions or resetting predictions until 11/20/2022.

**Comment by efyasar** [comment]
By default, the app only allows making new predictions or resetting predictions until 11/20/2022.
