### ISSUE TITLE
New users entering predictions although World Cup already started

### ISSUE THREAD

**Issue by caznaran** [efyasar/world-cup-prediction-game#4]
Hi, while predictions are now unable to be reset as of November 20th, new users are entering their predictions during the day.

Is there a way to prevent new users to enter their predictions? We don't want new users to enter the predictions at the end of the group phase while having all the actual results on hand, or even in the finals.

**Comment by efyasar** [comment]
Hello,

Please update your solution with latest version, first. 
[How to update the app? ](https://github.com/efyasar/football-world-championship-prediction-game/wiki/How-to-Update-the-app)

Then you can review this article to set deadline of the prediction.
[How to change the prediction deadline](https://github.com/efyasar/football-world-championship-prediction-game/wiki/How-to-change-the-prediction-deadline)

**Comment by caznaran** [comment]
Please take a look at this:

![image](https://user-images.githubusercontent.com/65054557/202948401-b6598be1-5096-4e91-ba6a-ae3cb97ef714.png)

![image](https://user-images.githubusercontent.com/65054557/202949373-e41fcc27-2cda-4651-b91c-5cb38294ad55.png)

**Comment by efyasar** [comment]
You can add "**en-US**" definition by manually or you can update your solution with [latest version](https://github.com/efyasar/football-world-championship-prediction-game/wiki/How-to-Update-the-app). 

1. Open Teams and Open the **Power Apps** application. Select **the environment** that you import the prediction game. Go to **Build** tab and then select **See All**. Select **the FWC Prediction Game** app and **Edit**.

![1_1](https://user-images.githubusercontent.com/832062/202896254-aaaef631-47cc-4e9e-a4a6-97cc787c2ca6.png)

2. Select the **App** from the **left menu** and open the **OnStart** event. Then update the date value. Please don't remove or change the "**en-US**" definition.

![2_2](https://user-images.githubusercontent.com/832062/202896324-86ec489a-6cf0-4510-a7df-548992539897.png)

3. Select the **ResultScreen** and then select **btn_Results_Info** component from the left menu. Select and edit the **Text** property with formula, update the date. Please don't remove or change the "**en-US**" definition.

![3_3](https://user-images.githubusercontent.com/832062/202896353-42f38293-2e8a-4907-bddd-ce5deebe8fad.png)

4. **Save** the application and go to **Build** Tab. Select the **FWC Prediction Game** and **publish** it. (**Details** => **Versions** => publish the last version)

![4](https://user-images.githubusercontent.com/832062/202897707-db1f114f-8e44-4c03-bf54-89cb6d1ce876.png)
