### ISSUE TITLE
Prediction section is not showing complete

### ISSUE THREAD

**Issue by rmerino06** [efyasar/world-cup-prediction-game#6]
We extend the prediction deadline and now the prediction section isn't showing the options complete. 
<img width="411" alt="Capture" src="https://user-images.githubusercontent.com/71419554/203868383-b552b504-8fd4-46e6-8a08-ccad2ddfe3ef.PNG">

any idea why?

**Comment by efyasar** [comment]
It might be a cache problem, try reloading (refresh) the app first. If the problem persists, please check if you have made a mistake in the formulas while editing the date. When you open the app in Edit mode, you can check for a formula error in App Checker.

**Comment by efyasar** [comment]
We cannot reproduce the issue on our development or test tenant. Can you please provide more details?
Can you please share the formula lines you edited to change the deadline?

**Comment by rmerino06** [comment]
This is the image of the formula
<img width="434" alt="Capture" src="https://user-images.githubusercontent.com/71419554/203995098-08085cf2-51a5-40b8-951d-b5d9a892c04a.PNG">
Now we are after deadline and new predictions are disable so it's not a big deal now. Just wondering why this could happen. Thanks.

**Comment by efyasar** [comment]
Hello,
Do you have any formula error in App Checker?
Also, you can update your application with latest version from [here](https://github.com/efyasar/football-world-championship-prediction-game/wiki/How-to-Update-the-app).

**Comment by rmerino06** [comment]
Yeah, I had the last version. And no error in App Checker. But don't worry, now the predictions are disable. Thanks anyway.
